# Generated by Django 5.2 on 2025-04-22 19:43

import django.db.models.deletion
import skilltree.model_data.models.skill_point
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0002_skillnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=skilltree.model_data.models.skill_point.get_attachment_path)),
                ('points', models.PositiveSmallIntegerField(default=1, help_text='How many points should this count as')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_points', to='skilltree.skillnode')),
            ],
        ),
    ]
