# Generated by Django 5.2 on 2025-04-22 19:56

import django.db.models.deletion
import skilltree.model_data.models.badge
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0003_skillpoint'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to=skilltree.model_data.models.badge.get_badge_image_path)),
                ('skill_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge', to='skilltree.skillnode')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='user.userprofile')),
            ],
        ),
    ]
