# To run hooks on all files, not just those staged for changes:
#   pre-commit run --all-files --config .pre-commit-config.yaml
# See https://pre-commit.com for more information.
# See https://pre-commit.com/hooks.html for more hooks.
default_language_version:
  python: python3.11.2
default_stages: [commit, push]
repos:
  # Run before the Python autoformatter, otherwise modifications made by this tool will require
  # formatting after `pre-commit` finishes
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.3
    hooks:
      - id: reorder-python-imports
        exclude: "/migrations/"
  # Run before the Python autoformatter
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.0.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
        exclude: "/migrations/"
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.4"]
        args: [--line-length=79]
        exclude: "/migrations/"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: end-of-file-fixer
        exclude_types: [svg]
        # Exclude yaml files because prettier formats those
        exclude: ".*\\.(yaml|yml)$"
      - id: check-added-large-files
      - id: check-yaml
        args: [--allow-multiple-documents]
        # Exclude Jinja templates that generate YAML files
        exclude: ".*\\.j2\\.yaml"
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: ["pep8-naming==0.9.1"]
        args: ["--show-source"]
        exclude: "/migrations/|__init__.py"
  - repo: https://github.com/myint/autoflake
    rev: v1.6.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
          ]
        exclude: "/migrations/"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.0.5
    hooks:
      - id: prettier
        # We use the following entry to override the entry provided by:
        # https://github.com/pre-commit/mirrors-prettier/blob/main/.pre-commit-hooks.yaml
        # This ensures the --ignore-unknown option is excluded so that we don't get warnings:
        # `[warn] Ignored unknown option --ignore-unknown`.
        # See: https://github.com/pre-commit/mirrors-prettier/issues/6
        entry: prettier --write --list-different
        # Pin node version to 17.9.1 as node 18 requires GLIBC_2.28, which is not currently on
        # devpod images.
        language_version: 17.9.1
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |html\
          |js\
          |jsx\
          |json\
          |mdx\
          |ts\
          |tsx\
          |test.js\
          |vue\
          |yaml\
          |yml\
          )$"
        exclude: '/static/|/templates/|polymer\.json|package\.json|package-lock\.json|next-env.d.ts|/minimal-ui/'
  - repo: https://github.com/doublify/pre-commit-clang-format
    rev: f4c4ac5948aff384af2b439bfabb2bdd65d2b3ac
    hooks:
      - id: clang-format
        exclude_types: [javascript]
        exclude: "Dockerfile.*"
        args: [-style=file]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.26.0
    hooks:
      - id: eslint
        args:
          - "--ext=.js,.jsx,.ts,.tsx"
          - "--max-warnings=0"
          - "--fix"
        exclude: "/static/|/templates/|/minimal-ui/|next.config.ts"
        files: \.(ts|tsx|js|jsx)$
        types: [file]
        working_directory: frontend/nosylos
