services:
  backend:
    container_name: django-app
    build:
      context: ./backend/nosylos_api
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - local.env
    depends_on:
      - db
      - minio
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_STORAGE_BUCKET_NAME: assets-bucket
      AWS_S3_ENDPOINT_URL: http://172.18.0.3:9000

  frontend:
    container_name: nextjs-app
    build:
      context: ./frontend/nosylos
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/nosylos:/app/nosylos
      - node_modules:/app/nosylos/node_modules
    restart: always
    environment:
      - WATCHPACK_POLLING=true

  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword

  minio:
    image: minio/minio
    container_name: minio-s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
  node_modules:
