# Generated by Django 4.0 on 2023-01-30 10:33

from django.db import migrations, models
import user.model_data.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_newsletter_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=user.model_data.models.user.create_uuid, max_length=35, primary_key=True, serialize=False),
        ),
    ]
