# Generated by Django 4.0 on 2023-12-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_newsletter_subscribed_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
